version: "3"

volumes:
  postgres-data:
  redis-data:

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./public:/var/www/habit-mosaic:ro"
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    command: redis-server --appendonly yes
  postgres:
    image: 'postgres:14.4'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
  maildev:
    image: maildev/maildev
    ports:
      - ${MAILDEV_PORT:-1080}:${MAILDEV_PORT:-1080}
    command: '-s ${MAIL_PORT:-1025} -w ${MAILDEV_PORT:-1080}'
  app:
    build:
      context: .
      args:
        WWW_USER: '${WWW_USER}'
        WWW_GROUP: '${WWW_GROUP}'
    volumes:
      - '.:/var/www'
    user: '${WWW_USER}'
  app-cron:
    build:
      context: .
      args:
        WWW_USER: '${WWW_USER}'
        WWW_GROUP: '${WWW_GROUP}'
    command: 'cron -f -l 2'
    volumes:
      - '.:/var/www'
  app-queue-default:
    build:
      context: .
      args:
        WWW_USER: '${WWW_USER}'
        WWW_GROUP: '${WWW_GROUP}'
    networks:
      - backend
    volumes:
      - '.:/var/www'
    user: '${WWW_USER}'
    command: 'queue:work --queue=default'
