#!/usr/bin/env bash
# get bash colors and styles here:
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd, filters)
{
    local color output exitcode

    filters=${4:-"\.php$"}

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"

    output=$(eval "git diff --diff-filter=M --name-only --cached | grep -E \"$filters\" | $3"  2>&1)

    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        echo -e "${C_GREEN}OK!${C_RESET}"
    else
        echo -e "${C_RED}NOK!${C_RESET}\n\n$output"
        exit 1
    fi
}

__run "1/6" "php lint" "xargs -I {} -r php -l {}"
__run "2/6" "php cbf" "xargs -r vendor/bin/phpcbf --no-colors"
__run "3/6" "code sniffer" "xargs -r vendor/bin/phpcs --no-colors"
__run "4/6" "phpstan" "xargs -r vendor/bin/phpstan analyse -c phpstan.neon" '^app/.*\.php$'
__run "5/6" "phpmd" "xargs -rI {} vendor/bin/phpmd {} text phpmd.xml" '^app/.*\.php$'
__run "6/6" "eslint" "xargs -rI {} npx eslint --cache --no-color {}" '^resources/js/.*\.(ts|js|vue)$'
