name: CI
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/cache@v3
        with:
           path: .eslintcache
           key: eslint-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.eslintrc.js') }}
      - run: npm ci
      - run: npm test
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: reports/eslint.sarif
          wait-for-processing: true
  phpstan:
    runs-on: ubuntu-latest
    needs: [phpcs]
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: php-actions/composer@v6
        with:
          php_version: 8.2
      - run: vendor/bin/phpstan analyse -c phpstan.neon --no-progress --error-format=checkstyle > reports/phpstan.xml
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        if: always()
        with:
          path: 'reports/phpstan.xml'
          name: phpstan report
  phpcs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: php-actions/composer@v6
      - uses: php-actions/phpcs@v1
        with:
          path: ./
          standard: phpcs.xml
          report: checkstyle
          report_file: reports/phpcs.xml
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        if: always()
        with:
          path: 'reports/phpcs.xml'
          name: phpcs report
  phpmd:
    runs-on: ubuntu-latest
    needs: [phpcs]
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: php-actions/composer@v6
      - uses: php-actions/phpmd@v1
        with:
          path: app
          output: sarif
          ruleset: phpmd.xml
          reportfile: reports/phpmd.sarif
          args: -vvv --ignore-errors-on-exit
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: reports/phpmd.sarif
          wait-for-processing: true
  phpunit:
    runs-on: ubuntu-latest
    needs: [phpcs]
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          log_junit: "reports/phpunit.xml"
          php_extensions: "xdebug"
          coverage_cobertura: "reports/coverage.xml"
        env:
          XDEBUG_MODE: coverage
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: reports/phpunit.xml
      - uses: 5monkeys/cobertura-action@master
        with:
          path: reports/coverage.xml
          minimum_coverage: 75
          show_line: true
          show_branch: true
          show_class_names: true
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [eslint,phpcs,phpunit]
    steps:
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: ${{ secrets.SSH_SCRIPT }}
