name: CI
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/cache@v3
        with:
           path: .eslintcache
           key: eslint-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.eslintrc.js') }}
      - run: npm ci
      - run: npm test
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: reports/eslint.sarif
          wait-for-processing: true
  phpstan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - run: vendor/bin/phpstan analyse -c phpstan.neon --no-progress --error-format=checkstyle > reports/phpstan.xml
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        if: always()
        with:
          path: 'reports/phpstan.xml'
  phpcs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - uses: php-actions/phpcs@v1
        with:
          path: ./
          standard: phpcs.xml
          report: checkstyle
          report_file: reports/phpcs.xml
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        if: always()
        with:
          path: 'reports/phpcs.xml'
  phpmd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - uses: php-actions/phpmd@v1
        with:
          path: app
          output: sarif
          ruleset: phpmd.xml
          reportfile: reports/phpmd.sarif
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: reports/phpmd.sarif
          wait-for-processing: true
  phpunit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - run: php artisan key:generate
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          log_junit: "reports/phpunit.xml"
          php_extensions: "xdebug"
          coverage_clover: "reports/clover.xml"
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: reports/phpunit.xml
      - uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          clover-file: reports/clover.xml
