name: Code Quality
on: ["push"]
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/cache@v3
        with:
           path: .eslintcache
           key: eslint-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.eslintrc.js') }}
      - run: npm ci
      - run: npm test
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
